<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>hadir-status-verify</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="HadirDesktop">
      <HintPath>../../HadirDesktop/bin/Debug/net8.0-windows/HadirDesktop.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
